<?php

return [
  /* Configure dashboard module */
  'dashboard' => [
    'name' => 'Dashboard'
  ],

  /* Configure product module */
  'product' => [
    'active' => true,
    'name' => 'Quản lý sản phẩm',
    'type' => 'product',
    'slug' => true,
    'code' => true,
    'copy' => true,
    'number_per_page' => 10,
    'sale_price' => true,
    'regular_price' => true,
    'discount' => true,
    'status' => [
      'banchay' => 'Bán chạy',
      'noibat' => 'Nổi bật',
      'hienthi' => 'Hiển thị'
    ],
    'desc' => true,
    'desc_tiny' => true,
    'content' => true,
    'content_tiny' => true,
    'photo1' => true,
    'thumb1' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
    'photo2' => false,
    'thumb2' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
    'photo3' => false,
    'thumb3' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
    'photo4' => false,
    'thumb4' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
    'gallery' => [
      'active' => true,
      'thumb' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)'
    ],
    'size' => false,
    'color' => false,
    'category' => [
      'name' => 'Danh mục sản phẩm',
      'active' => true,
      'category1' => [
        'active' => true,
        'copy' => true,
        'name' => 'Danh mục cấp 1',
        'type' => 'product',
        'number_per_page' => 10,
        'status' => [
          'noibat' => 'Nổi bật',
          'hienthi' => 'Hiển thị'
        ],
        'slug' => true,
        'desc' => true,
        'desc_tiny' => true,
        'content' => true,
        'content_tiny' => true,
        'photo1' => true,
        'thumb1' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo2' => false,
        'thumb2' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo3' => false,
        'thumb3' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo4' => false,
        'thumb4' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'seo' => true,
        'seo_title' => true,
        'seo_keyword' => true,
        'seo_desc' => true
      ],
      'category2' => [
        'active' => true,
        'copy' => true,
        'name' => 'Danh mục cấp 2',
        'type' => 'product',
        'number_per_page' => 10,
        'status' => [
          'noibat' => 'Nổi bật',
          'hienthi' => 'Hiển thị'
        ],
        'slug' => true,
        'desc' => true,
        'desc_tiny' => true,
        'content' => true,
        'content_tiny' => true,
        'photo1' => true,
        'thumb1' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo2' => false,
        'thumb2' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo3' => false,
        'thumb3' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo4' => false,
        'thumb4' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'seo' => true,
        'seo_title' => true,
        'seo_keyword' => true,
        'seo_desc' => true
      ],
      'category3' => [
        'active' => true,
        'copy' => true,
        'name' => 'Danh mục cấp 3',
        'type' => 'product',
        'number_per_page' => 10,
        'status' => [
          'noibat' => 'Nổi bật',
          'hienthi' => 'Hiển thị'
        ],
        'slug' => true,
        'desc' => true,
        'desc_tiny' => true,
        'content' => true,
        'content_tiny' => true,
        'photo1' => true,
        'thumb1' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo2' => false,
        'thumb2' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo3' => false,
        'thumb3' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo4' => false,
        'thumb4' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'seo' => true,
        'seo_title' => true,
        'seo_keyword' => true,
        'seo_desc' => true
      ],
      'category4' => [
        'active' => true,
        'copy' => true,
        'name' => 'Danh mục cấp 4',
        'type' => 'product',
        'number_per_page' => 10,
        'status' => [
          'noibat' => 'Nổi bật',
          'hienthi' => 'Hiển thị'
        ],
        'slug' => true,
        'desc' => true,
        'desc_tiny' => true,
        'content' => true,
        'content_tiny' => true,
        'photo1' => true,
        'thumb1' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo2' => false,
        'thumb2' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo3' => false,
        'thumb3' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo4' => false,
        'thumb4' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'seo' => true,
        'seo_title' => true,
        'seo_keyword' => true,
        'seo_desc' => true
      ],
    ],
    'seo' => true,
    'seo_title' => true,
    'seo_keyword' => true,
    'seo_desc' => true,
    'schema' => true
  ],

  /* Configure news module */
  'news' => [
    'active' => true,
    'name' => 'Quản lý tin tức',
    'type' => 'news',
    'slug' => true,
    'code' => true,
    'copy' => true,
    'number_per_page' => 10,
    'status' => [
      'banchay' => 'Bán chạy',
      'noibat' => 'Nổi bật',
      'hienthi' => 'Hiển thị'
    ],
    'desc' => true,
    'desc_tiny' => true,
    'content' => true,
    'content_tiny' => true,
    'photo1' => true,
    'thumb1' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
    'photo2' => false,
    'thumb2' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
    'photo3' => false,
    'thumb3' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
    'photo4' => false,
    'thumb4' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
    'gallery' => [
      'active' => true,
      'thumb' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)'
    ],
    'category' => [
      'name' => 'Danh mục tin tức',
      'active' => true,
      'category1' => [
        'active' => true,
        'copy' => true,
        'name' => 'Danh mục cấp 1',
        'type' => 'news',
        'number_per_page' => 10,
        'status' => [
          'noibat' => 'Nổi bật',
          'hienthi' => 'Hiển thị'
        ],
        'slug' => true,
        'desc' => true,
        'desc_tiny' => true,
        'content' => true,
        'content_tiny' => true,
        'photo1' => true,
        'thumb1' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo2' => false,
        'thumb2' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo3' => false,
        'thumb3' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo4' => false,
        'thumb4' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'seo' => true,
        'seo_title' => true,
        'seo_keyword' => true,
        'seo_desc' => true
      ],
      'category2' => [
        'active' => true,
        'copy' => true,
        'name' => 'Danh mục cấp 2',
        'type' => 'news',
        'number_per_page' => 10,
        'status' => [
          'noibat' => 'Nổi bật',
          'hienthi' => 'Hiển thị'
        ],
        'slug' => true,
        'desc' => true,
        'desc_tiny' => true,
        'content' => true,
        'content_tiny' => true,
        'photo1' => true,
        'thumb1' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo2' => false,
        'thumb2' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo3' => false,
        'thumb3' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo4' => false,
        'thumb4' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'seo' => true,
        'seo_title' => true,
        'seo_keyword' => true,
        'seo_desc' => true
      ],
      'category3' => [
        'active' => true,
        'copy' => true,
        'name' => 'Danh mục cấp 3',
        'type' => 'news',
        'number_per_page' => 10,
        'status' => [
          'noibat' => 'Nổi bật',
          'hienthi' => 'Hiển thị'
        ],
        'slug' => true,
        'desc' => true,
        'desc_tiny' => true,
        'content' => true,
        'content_tiny' => true,
        'photo1' => true,
        'thumb1' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo2' => false,
        'thumb2' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo3' => false,
        'thumb3' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo4' => false,
        'thumb4' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'seo' => true,
        'seo_title' => true,
        'seo_keyword' => true,
        'seo_desc' => true
      ],
      'category4' => [
        'active' => true,
        'copy' => true,
        'name' => 'Danh mục cấp 4',
        'type' => 'news',
        'number_per_page' => 10,
        'status' => [
          'noibat' => 'Nổi bật',
          'hienthi' => 'Hiển thị'
        ],
        'slug' => true,
        'desc' => true,
        'desc_tiny' => true,
        'content' => true,
        'content_tiny' => true,
        'photo1' => true,
        'thumb1' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo2' => false,
        'thumb2' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo3' => false,
        'thumb3' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'photo4' => false,
        'thumb4' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
        'seo' => true,
        'seo_title' => true,
        'seo_keyword' => true,
        'seo_desc' => true
      ],
    ],
    'seo' => true,
    'seo_title' => true,
    'seo_keyword' => true,
    'seo_desc' => true,
    'schema' => true
  ],

  /* Configure post module */
  'post' => [
    'active' => true,
    'name' => 'Quản lý bài viết',
    'table' => 'news',
    'criteria' => [
      'active' => true,
      'name' => 'Tiêu chí',
      'type' => 'criteria',
      'status' => ['hienthi' => 'Hiển thị'],
      'desc' => true,
      'slug' => false,
      'photo1' => true,
      'thumb1' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
      'photo2' => false,
      'thumb2' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
      'photo3' => false,
      'thumb3' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
      'photo4' => false,
      'thumb4' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
      'seo' => false
    ],
    'policy' => [
      'active' => true,
      'name' => 'Chính sách',
      'type' => 'policy',
      'slug' => true,
      'status' => ['hienthi' => 'Hiển thị'],
      'content' => true,
      'content_tiny' => true,
      'photo1' => true,
      'thumb1' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
      'photo2' => false,
      'thumb2' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
      'photo3' => false,
      'thumb3' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
      'photo4' => false,
      'thumb4' => 'Width: 282 px - Height: 370 px (.jpg|.gif|.png|.jpeg|.gif)',
      'seo' => true,
      'seo_title' => true,
      'seo_keyword' => true,
      'seo_desc' => true
    ]
  ],

  /* Configure static module */
  'static' => [],

  /* Configure seopage module */
  'seopage' => [],

  /* Configure photo module */
  'photo' => [],

  /* Configure setting module */
  'setting' => [],

];
